
For Category table:


INSERT INTO `LIFESTYLE_DB`.`CATEGORY` ( `CREATED_BY`, `IS_ACTIVE`, `CTGRY_NAME`, `CTGRY_ONE`, `CTGRY_SUBTYPE1`, `CTGRY_SUBTYPE2`, `CTGRY_SUBTYPE3`, `CTGRY_THREE`, `CTGRY_TWO`) VALUES ('admin', '1', 'clothes', 'color', 'one', 'two', 'three', 'gender', 'type');


INSERT INTO `LIFESTYLE_DB`.`CATEGORY` ( `CREATED_BY`, `IS_ACTIVE`, `CTGRY_NAME`, `CTGRY_ONE`, `CTGRY_SUBTYPE1`, `CTGRY_SUBTYPE2`, `CTGRY_SUBTYPE3`, `CTGRY_THREE`, `CTGRY_TWO`) VALUES ('admin', '1', 'shoes', 'color', 'one', 'two', 'three', 'gender', 'type');


INSERT INTO `LIFESTYLE_DB`.`CATEGORY` ( `CREATED_BY`, `IS_ACTIVE`, `CTGRY_NAME`, `CTGRY_ONE`, `CTGRY_SUBTYPE1`, `CTGRY_SUBTYPE2`, `CTGRY_SUBTYPE3`, `CTGRY_THREE`, `CTGRY_TWO`) VALUES ('admin', '1', 'watches', 'color', 'one', 'two', 'three', 'gender', 'type');

For Merchant table:

INSERT INTO `LIFESTYLE_DB`.`MERCHANT` ( `CREATED_BY`, `IS_ACTIVE`, `MODIFIED_BY`, `MERCHANT_NAME`) VALUES ( 'admin', '1', 'admin', 'Puma');


INSERT INTO `LIFESTYLE_DB`.`MERCHANT` ( `CREATED_BY`, `IS_ACTIVE`, `MODIFIED_BY`, `MERCHANT_NAME`) VALUES ( 'admin', '1', 'admin', 'Adidas');

INSERT INTO `LIFESTYLE_DB`.`MERCHANT` ( `CREATED_BY`, `IS_ACTIVE`, `MODIFIED_BY`, `MERCHANT_NAME`) VALUES ('admin', '1', 'admin', 'Nike');



CUSTOMER_DATA

INSERT INTO `LIFESTYLE_DB`.`CUSTOMER_DATA` ( `CREATED_BY`, `IS_ACTIVE`, `MODIFIED_BY`, `PASSWORD`, `USERNAME`) VALUES ('1', 'admin', '1', 'admin', '$2a$10$fu6Y8SPc4l5Zzzk7JWhi/evuraiOLGt1IXpQld06pZK/2BCBpi32G', 'admin');


INSERT INTO `LIFESTYLE_DB`.`CUSTOMER_DATA` ( `CREATED_BY`, `IS_ACTIVE`, `MODIFIED_BY`, `PASSWORD`, `USERNAME`) VALUES ( 'user', '1', 'user', '$2a$10$02yws5leHet5cyycGyMkleul.oGtJJ7ER8itI4ddGwslHZBA2hXGe', 'user');



ROLE:

INSERT INTO `LIFESTYLE_DB`.`ROLES` ( `CREATED_BY`, `IS_ACTIVE`, `ROLE_NAME`) VALUES ( 'admin', '1', 'ROLE_ADMIN');
INSERT INTO `LIFESTYLE_DB`.`ROLES` ( `CREATED_BY`, `IS_ACTIVE`, `ROLE_NAME`) VALUES ( 'user', '1', 'ROLE_USER');


USER_ROLES

INSERT INTO `LIFESTYLE_DB`.`USER_ROLES` (`USER_ID`, `ROLE_ID`) VALUES ('1', '1');

INSERT INTO `LIFESTYLE_DB`.`USER_ROLES` (`USER_ID`, `ROLE_ID`) VALUES ('2', '2');







